# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "dalta-leabharlann-resolve-book-information"
main = "src/index.ts"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[queues.consumers]]
queue = "test-queue"
max_batch_size = 1
max_batch_timeout = 1
max_retries = 3
dead_letter_queue = "test-dlq"
